CREATE TABLE IF NOT EXISTS mytodos(
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) UNIQUE NOT NULL,
    description VARCHAR(255) NOT NULL,
    isCompleted BOOLEAN DEFAULT FALSE,
    createdAt_UTC TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updatedAt_UTC TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    user_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES todoUsers(userId)
);